- name: Adding GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Getting OS release
  ansible.builtin.shell:
    cmd: echo $(. /etc/os-release && echo "$VERSION_CODENAME")
  register: os_release
  changed_when: false

- name: Adding docker APT repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu "{{ os_release.stdout }}" stable
    state: present

- name: Finally Installing docker
  ansible.builtin.apt:
    package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
